"""
main.py - FastAPI Application Server
=====================================
This is the REST API that serves the trained LSTM model.
It loads the model on startup and exposes endpoints for:
  - Text generation
  - Model information
  - Training history visualization
  - Health check

Run with:
    uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

API Documentation (auto-generated by FastAPI):
    http://localhost:8000/docs    (Swagger UI)
    http://localhost:8000/redoc  (ReDoc)

CORS is enabled for all origins -- in production, restrict to your frontend's domain.
"""

import os
import io
import json
import base64
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, HTTPException, Response
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field, field_validator

from app.text_generator import TextGenerator


# ─── PYDANTIC MODELS (Request/Response Schemas) ──────────────────────────────
# Pydantic models define the shape of API request and response bodies.
# FastAPI uses these for automatic validation and documentation.

class GenerateRequest(BaseModel):
    """Schema for text generation requests."""
    seed_text: str = Field(
        ...,
        min_length=1,
        max_length=500,
        description="Starting text for generation",
        examples=["the cat sat on"]
    )
    num_words: int = Field(
        default=50,
        ge=1,
        le=500,
        description="Number of words to generate"
    )
    temperature: float = Field(
        default=1.0,
        ge=0.1,
        le=3.0,
        description="Sampling temperature: 0.5=conservative, 1.0=balanced, 1.5=creative"
    )

    @field_validator('seed_text')
    @classmethod
    def seed_text_not_empty(cls, v):
        if not v.strip():
            raise ValueError('seed_text cannot be empty or whitespace only')
        return v.strip()


class GenerateResponse(BaseModel):
    """Schema for text generation responses."""
    seed_text: str
    generated_text: str
    num_words_requested: int
    temperature: float
    model_info: dict


class ModelInfoResponse(BaseModel):
    """Schema for model information responses."""
    status: str
    vocab_size: Optional[int] = None
    sequence_length: Optional[int] = None
    total_parameters: Optional[int] = None
    layers: Optional[list] = None
    config: Optional[dict] = None


# ─── FASTAPI APPLICATION ──────────────────────────────────────────────────────

app = FastAPI(
    title="RNN Text Generator API",
    description="""
    ## LSTM Text Generation API

    This API serves a trained LSTM model for text generation.

    ### How it works:
    1. Train a model using `python train.py`
    2. Start this server: `uvicorn app.main:app --reload`
    3. Send POST requests to `/generate` with a seed text
    4. The LSTM model generates continuation text

    ### Frontend Integration:
    This API can be consumed by any HTTP client:
    - Streamlit frontend (provided)
    - React/Vue/Angular web app
    - Mobile app
    - Command line (curl)
    """,
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc"
)

# ── CORS Middleware ────────────────────────────────────────────────────────────
# Cross-Origin Resource Sharing: allows the frontend (different port/domain)
# to make requests to this API.
# In production: replace allow_origins=["*"] with your actual frontend URL
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],           # Allow all origins (frontend can be anywhere)
    allow_credentials=True,
    allow_methods=["*"],           # Allow GET, POST, OPTIONS, etc.
    allow_headers=["*"],           # Allow all headers
)

# ── Global model instance ──────────────────────────────────────────────────────
# The model is loaded once at startup and reused for all requests
text_generator: Optional[TextGenerator] = None
MODEL_DIR = os.environ.get("MODEL_DIR", "models")


# ─── STARTUP EVENT ────────────────────────────────────────────────────────────

@app.on_event("startup")
async def load_model():
    """
    Load the trained model when the server starts.

    This runs once before the server accepts any requests.
    If no trained model is found, the server starts anyway but
    generation endpoints will return a 503 error.
    """
    global text_generator
    text_generator = TextGenerator()

    model_path = os.path.join(MODEL_DIR, 'model.pt')
    if os.path.exists(model_path):
        try:
            text_generator.load(MODEL_DIR)
            print(f"Model loaded successfully from {MODEL_DIR}/")
            info = text_generator.get_model_info()
            print(f"  Vocabulary size: {info.get('vocab_size', 'N/A')}")
            print(f"  Total parameters: {info.get('total_parameters', 'N/A'):,}")
        except Exception as e:
            print(f"Failed to load model: {e}")
            print("  Start the server anyway -- train a model first using train.py")
            text_generator = None
    else:
        print(f"No trained model found at {model_path}")
        print("  Run 'python app/train.py' to train a model first")
        text_generator = None


# ─── API ENDPOINTS ────────────────────────────────────────────────────────────

@app.get("/", tags=["Health"])
async def root():
    """
    Health check endpoint.
    Returns server status and whether the model is loaded.
    """
    model_loaded = text_generator is not None and text_generator.model is not None
    return {
        "status": "running",
        "model_loaded": model_loaded,
        "message": "RNN Text Generator API is running",
        "docs": "/docs"
    }


@app.get("/health", tags=["Health"])
async def health_check():
    """Lightweight health check for load balancers."""
    return {"status": "healthy"}


@app.post("/generate", response_model=GenerateResponse, tags=["Generation"])
async def generate_text(request: GenerateRequest):
    """
    Generate text continuation from a seed phrase.

    ## How this works:
    1. Receives seed_text, num_words, temperature in request body
    2. Passes to TextGenerator.generate_text()
    3. LSTM model auto-regressively generates num_words new words
    4. Returns the full text (seed + generated) with metadata

    ## Temperature guide:
    - **0.5**: Conservative -- predictable, less varied output
    - **1.0**: Balanced -- model's natural distribution
    - **1.5**: Creative -- more varied, occasionally surprising

    ## Example:
    ```json
    {
        "seed_text": "the cat sat on",
        "num_words": 30,
        "temperature": 1.0
    }
    ```
    """
    if text_generator is None or text_generator.model is None:
        raise HTTPException(
            status_code=503,
            detail={
                "error": "Model not loaded",
                "message": "No trained model found. Run 'python train.py' first.",
                "fix": "cd backend && python app/train.py"
            }
        )

    try:
        generated = text_generator.generate_text(
            seed_text=request.seed_text,
            num_words=request.num_words,
            temperature=request.temperature
        )

        return GenerateResponse(
            seed_text=request.seed_text,
            generated_text=generated,
            num_words_requested=request.num_words,
            temperature=request.temperature,
            model_info={
                "vocab_size": text_generator.vocab_size,
                "sequence_length": text_generator.sequence_length,
            }
        )

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail={"error": "Generation failed", "message": str(e)}
        )


@app.get("/model/info", response_model=ModelInfoResponse, tags=["Model"])
async def get_model_info():
    """
    Get information about the loaded model.

    Returns vocabulary size, architecture details, parameter count, and configuration.
    """
    if text_generator is None:
        return ModelInfoResponse(status="not_loaded")

    info = text_generator.get_model_info()
    return ModelInfoResponse(**info)


@app.get("/model/architecture-image", tags=["Model"])
async def get_architecture_image():
    """Return a base64-encoded PNG of the model architecture diagram."""
    if text_generator is None or text_generator.model is None:
        raise HTTPException(status_code=503, detail="Model not loaded")

    try:
        import matplotlib.pyplot as plt
        import matplotlib.patches as mpatches

        fig, ax = plt.subplots(figsize=(8, 10))
        fig.patch.set_facecolor('#1e1e2e')
        ax.set_facecolor('#1e1e2e')
        ax.set_xlim(0, 10)
        ax.set_ylim(0, 12)
        ax.axis('off')

        layers_info = [
            ("Input",          f"shape: (batch, {text_generator.sequence_length})",                    "#7c6af5"),
            ("nn.Embedding",   f"({text_generator.vocab_size} → {text_generator.embedding_dim})",      "#6a8ef5"),
            ("nn.LSTM  layer1", f"input={text_generator.embedding_dim}, hidden={text_generator.lstm_units}, all timesteps", "#6af5c8"),
            ("nn.Dropout",     f"p={text_generator.dropout_rate}",                                    "#f5d76a"),
            ("nn.LSTM  layer2", f"input={text_generator.lstm_units},  hidden={text_generator.lstm_units}, final h_T only",  "#6af5c8"),
            ("nn.Dropout",     f"p={text_generator.dropout_rate}",                                    "#f5d76a"),
            ("nn.Linear",      f"({text_generator.lstm_units} → {text_generator.vocab_size}) + softmax at inference", "#f56a6a"),
        ]

        y_positions = [10.5, 9, 7.5, 6.2, 4.7, 3.4, 1.9]
        for i, ((name, detail, color), y) in enumerate(zip(layers_info, y_positions)):
            rect = mpatches.FancyBboxPatch(
                (1.5, y - 0.5), 7, 0.9,
                boxstyle="round,pad=0.1",
                facecolor=color + '33', edgecolor=color, linewidth=2
            )
            ax.add_patch(rect)
            ax.text(5, y, name, ha='center', va='center',
                    fontsize=12, fontweight='bold', color=color)
            ax.text(5, y - 0.3, detail, ha='center', va='center',
                    fontsize=8, color='#aaaacc')
            if i < len(y_positions) - 1:
                ax.annotate('', xy=(5, y_positions[i+1] + 0.4), xytext=(5, y - 0.5),
                           arrowprops=dict(arrowstyle='->', color='#888899', lw=1.5))

        ax.text(5, 11.5, 'LSTM Model Architecture',
                ha='center', fontsize=14, fontweight='bold', color='white')

        buf = io.BytesIO()
        plt.savefig(buf, format='png', dpi=100, bbox_inches='tight', facecolor='#1e1e2e')
        plt.close()
        buf.seek(0)
        img_base64 = base64.b64encode(buf.read()).decode()

        return {"image_base64": img_base64, "format": "png"}

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/training/history", tags=["Training"])
async def get_training_history():
    """
    Return training history (loss and accuracy per epoch) as JSON.
    Useful for plotting in the frontend.
    """
    if text_generator is None:
        raise HTTPException(status_code=503, detail="Model not loaded")

    history_path = os.path.join(MODEL_DIR, 'training_history.json')
    if os.path.exists(history_path):
        with open(history_path) as f:
            return json.load(f)
    elif text_generator.training_history:
        return text_generator.training_history
    else:
        raise HTTPException(
            status_code=404,
            detail="No training history found. Train the model first."
        )


@app.post("/generate/batch", tags=["Generation"])
async def generate_batch(request: GenerateRequest, variations: int = 3):
    """
    Generate multiple text variations from the same seed.
    Useful for comparing different outputs at the same temperature.

    - variations: Number of independent samples to generate (max 10)
    """
    if text_generator is None or text_generator.model is None:
        raise HTTPException(status_code=503, detail="Model not loaded")

    if variations > 10:
        raise HTTPException(status_code=400, detail="Maximum 10 variations")

    results = []
    for i in range(variations):
        generated = text_generator.generate_text(
            seed_text=request.seed_text,
            num_words=request.num_words,
            temperature=request.temperature
        )
        results.append({"variation": i + 1, "text": generated})

    return {
        "seed_text": request.seed_text,
        "temperature": request.temperature,
        "variations": results
    }
